-- 초기 데이터베이스 설정 예시
-- 이 파일은 컨테이너 최초 실행 시 자동으로 실행됩니다.

-- 샘플 테이블 생성 (선택사항)
-- USE mariadb;
-- 
-- CREATE TABLE IF NOT EXISTS users (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     username VARCHAR(50) NOT NULL UNIQUE,
--     email VARCHAR(100) NOT NULL UNIQUE,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- 
-- INSERT INTO users (username, email) VALUES 
--     ('admin', 'admin@example.com'),
--     ('user1', 'user1@example.com');
