[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log

[program:redis]
command=/usr/local/bin/redis-server /etc/redis/redis.conf
autorestart=true
stdout_logfile=/var/log/supervisor/redis.out.log
stderr_logfile=/var/log/supervisor/redis.err.log
priority=10

[program:sentinel]
command=/usr/local/bin/redis-server /etc/redis/sentinel.conf --sentinel
autorestart=true
stdout_logfile=/var/log/supervisor/sentinel.out.log
stderr_logfile=/var/log/supervisor/sentinel.err.log
priority=20
